Update all_in_one.yml

diff --git a/.github/workflows/all_in_one.yml b/.github/workflows/all_in_one.yml
--- a/.github/workflows/all_in_one.yml
+++ b/.github/workflows/all_in_one.yml
@@ -29,21 +29,36 @@ jobs:
       - id: setup
         name: Configuration setup
         run: |
-          split=(${GITHUB_REPOSITORY//\// })
-          echo "CALLER_REPO_NAME=${split[1]}" >> $GITHUB_OUTPUT
+            split=(${GITHUB_REPOSITORY//\// })
+            echo "CALLER_REPO_NAME=${split[1]}" >> $GITHUB_OUTPUT
 
-          if [ ${GITHUB_REF_TYPE} == 'tag' ]; then
-            if [ ${GITHUB_REF_NAME} == 'dev' ]; then
-              echo "TAG=dev" >> $GITHUB_OUTPUT
-              echo "RUNNER=apifornia-dev" >> $GITHUB_OUTPUT
+            if [ ${GITHUB_REF_TYPE} == 'tag' ]; then
+              if [ ${GITHUB_REF_NAME} == 'dev' ]; then
+                echo "TAG=dev" >> $GITHUB_OUTPUT
+                echo "RUNNER=apifornia-dev" >> $GITHUB_OUTPUT
+                OK="yes"
+              fi
+              if [ ${GITHUB_REF_NAME} == 'prod' ]; then
+                echo "TAG=dev" >> $GITHUB_OUTPUT
+                echo "RUNNER=apifornia-prod" >> $GITHUB_OUTPUT
+                OK="yes"
+              fi
             fi
-            if [ ${GITHUB_REF_NAME} == 'prod' ]; then
-              echo "TAG=dev" >> $GITHUB_OUTPUT
-              echo "RUNNER=apifornia-prod" >> $GITHUB_OUTPUT
+
+            if [ ${GITHUB_REF_TYPE} == 'branch' ]; then
+              if [ ${GITHUB_REF_NAME} == 'develop' ]; then
+                echo "TAG=dev" >> $GITHUB_OUTPUT
+                echo "RUNNER=apifornia-dev" >> $GITHUB_OUTPUT
+                OK="yes"
+              fi
             fi
-          else
-            exit 1
-          fi
+
+            if [ ${OK} == 'yes' ]; then
+              echo "All good"
+            else
+              echo "ERROR: deployment can't proceed"
+              exit 1
+            fi
   build:
     runs-on: apifornia-builder
     needs: setup
