Pr (#5)
TLDR

diff --git a/.github/workflows/all_in_one.yml b/.github/workflows/all_in_one.yml
--- a/.github/workflows/all_in_one.yml
+++ b/.github/workflows/all_in_one.yml
@@ -11,7 +11,19 @@ on:
         required: false
       env_file:
         type: string
-        default: 'docker/compose/dev/.env'
+        default: '.env'
+        required: false
+      do_build:
+        type: boolean
+        default: true
+        required: false
+      do_build_push:
+        type: boolean
+        default: true
+        required: false
+      do_deploy:
+        type: boolean
+        default: true
         required: false
     secrets:
       env_vars:
@@ -20,47 +32,13 @@ on:
 jobs:
   setup:
     runs-on: apifornia-builder
-    outputs:
-      CALLER_REPO_NAME: ${{ steps.setup.outputs.CALLER_REPO_NAME }}
-      RUNNER: ${{ steps.setup.outputs.RUNNER }}
-      TAG: ${{ steps.setup.outputs.TAG }}
-      BASE_DOMAIN: ${{ steps.setup.outputs.BASE_DOMAIN }}
     steps:
-      - id: setup
-        name: Configuration setup
-        run: |
-            split=(${GITHUB_REPOSITORY//\// })
-            echo "CALLER_REPO_NAME=${split[1]}" >> $GITHUB_OUTPUT
-
-            if [ ${GITHUB_REF_TYPE} == 'tag' ]; then
-              if [ ${GITHUB_REF_NAME} == 'dev' ]; then
-                echo "TAG=dev" >> $GITHUB_OUTPUT
-                echo "RUNNER=apifornia-dev" >> $GITHUB_OUTPUT
-                OK="yes"
-              fi
-              if [ ${GITHUB_REF_NAME} == 'prod' ]; then
-                echo "TAG=dev" >> $GITHUB_OUTPUT
-                echo "RUNNER=apifornia-prod" >> $GITHUB_OUTPUT
-                OK="yes"
-              fi
-            fi
-
-            if [ ${GITHUB_REF_TYPE} == 'branch' ]; then
-              if [ ${GITHUB_REF_NAME} == 'develop' ]; then
-                echo "TAG=dev" >> $GITHUB_OUTPUT
-                echo "RUNNER=apifornia-dev" >> $GITHUB_OUTPUT
-                OK="yes"
-              fi
-            fi
-
-            if [ ${OK} == 'yes' ]; then
-              echo "All good"
-            else
-              echo "ERROR: deployment can't proceed"
-              exit 1
-            fi
+      - name: Setup
+        uses: apifornia/github-actions/setup-logic@main
+  
   build:
     runs-on: apifornia-builder
+    if: "${{ inputs.do_build == true }}"
     needs: setup
     steps:
       - name: Checkout
@@ -78,7 +56,7 @@ jobs:
           images: ghcr.io/${{ github.repository }}
           tags: |
             type=raw,value=${{ github.sha }}
-            type=raw,value=latest
+            type=raw,value=${{ needs.setup.outputs.EXTRA_TAG }}
       
       - name: Login to GitHub Container Registry
         uses: docker/login-action@v2
@@ -92,15 +70,13 @@ jobs:
         with:
           context: .
           file: ${{ inputs.docker_file }}
-          push: true
+          push: ${{ inputs.do_build_push }}
           tags: ${{ steps.meta.outputs.tags }}
 
-      - name: Cleanup
-        run: |
-          docker image rm -f ${{ steps.meta.outputs.tags }} || true
-  compose-up:
+  deploy:
     needs: [setup,build]
-    runs-on: ${{ needs.setup.outputs.RUNNER }}
+    runs-on: ${{ needs.setup.outputs.DEPLOY_RUNNER }}
+    if: "${{ inputs.do_deploy == true }}"
     steps:
       - name: Checkout
         uses: actions/checkout@v3
@@ -160,16 +136,12 @@ jobs:
           -f ${{ inputs.compose_file }}
           --env-file ${{ inputs.env_file }}
           up --detach
-  # notify:
-  #   runs-on: apifornia-builder
-  # deploy-lint:
-  #   needs: [setup,build]
-  #   runs-on: ${{ needs.setup.outputs.RUNNER }}
-  #   steps:
-  #     - name: Compose Lint
-  #       run: |
-  #         /usr/local/bin/docker compose
-  #         --project-name ${CI_PROJECT_NAME}
-  #         --project-directory ${CI_APPLICATION_PATH:-/srv/app}/${CI_PROJECT_NAME}
-  #         --file ${BUILD_DOCKER_COMPOSEFILE:-docker-compose.yml}
-  #         config
+
+# commented because docker image cleanup job runs on the server each week
+#  post:
+#    runs-on: apifornia-builder
+#    needs: [setup,build,deploy]
+#    steps:
+#      - name: Cleanup
+#        run: |
+#          docker image rm -f ${{ steps.meta.outputs.tags }} || true
